jccm pkg osx sign and notarization

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,10 +9,45 @@ on:
 jobs:
     build-macos:
         runs-on: macos-latest
-        if: ${{ github.event.head_commit.message != 'Automated commit by GitHub Actions' }}
+        env:
+            APPLE_ID: ${{ secrets.APPLE_ID }}
+            APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
+            APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
+            DEBUG: electron-osx-sign*,electron-notarize*
+
         steps:
             - name: Check out repository
               uses: actions/checkout@v2
+
+            - name: Install signing certificate
+              run: |
+                  KEYCHAIN_NAME=build.keychain
+                  KEYCHAIN_PASSWORD=$(openssl rand -base64 12)
+
+                  echo "Decode signing certificate..."
+                  echo "${{ secrets.SIGNING_CERTIFICATE }}" | base64 --decode > signing_certificate.p12
+                  echo "${{ secrets.INSTALLING_CERTIFICATE }}" | base64 --decode > installing_certificate.p12
+
+                  echo "Creating keychain..."
+                  security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
+
+                  echo "Setting default keychain..."
+                  security default-keychain -s $KEYCHAIN_NAME
+
+                  echo "Unlocking keychain..."
+                  security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
+
+                  echo "Importing certificate..."
+                  security import signing_certificate.p12 -k $KEYCHAIN_NAME -P "${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
+                  security import installing_certificate.p12 -k $KEYCHAIN_NAME -P "${{ secrets.INSTALLING_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign -T /usr/bin/productbuild
+
+                  echo "Listing keychains..."
+                  security list-keychains -s $KEYCHAIN_NAME
+
+                  echo "Setting key partition list..."
+                  security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
+
+              working-directory: ./jccm
 
             - name: Set up Node.js
               uses: actions/setup-node@v2
@@ -27,46 +62,56 @@ jobs:
                   python3.9 -m ensurepip
                   python3.9 -m pip install --upgrade pip
                   python3.9 -m pip install setuptools
+
               working-directory: ./jccm
 
             - name: Install dependencies
               run: |
                   source myenv/bin/activate
                   npm install
+
               working-directory: ./jccm
 
             - name: Install appdmg
               run: |
                   source myenv/bin/activate
                   npm install --save-dev appdmg
+
               working-directory: ./jccm
 
-            - name: Install signing certificate
-              run: |
-                  KEYCHAIN_NAME=build.keychain
-                  KEYCHAIN_PASSWORD=$(openssl rand -base64 12)
-                  echo "Decode signing certificate..."
-                  echo "${{ secrets.SIGNING_CERTIFICATE }}" | base64 --decode > signing_certificate.p12
-                  echo "Creating keychain..."
-                  security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
-                  echo "Setting default keychain..."
-                  security default-keychain -s $KEYCHAIN_NAME
-                  echo "Unlocking keychain..."
-                  security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
-                  echo "Importing certificate..."
-                  security import signing_certificate.p12 -k $KEYCHAIN_NAME -P "${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
-                  echo "Listing keychains..."
-                  security list-keychains -s $KEYCHAIN_NAME
-                  echo "Setting key partition list..."
-                  security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
             - name: Build and package (arm64 and x64)
-              env:
-                  APPLE_ID: ${{ secrets.APPLE_ID }}
-                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
-                  APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
               run: |
                   source myenv/bin/activate
                   npm run make
+              working-directory: ./jccm
+
+            - name: Notarize and Staple Packages
+              run: |
+                  set -ex  # Exit on error and print commands
+
+                  function notarize_and_verify() {
+                      architecture=$1
+                      pkg_path="./out/make/jccm-darwin-$architecture.pkg"
+
+                      echo "Submitting $pkg_path for Notarization..."
+                      xcrun notarytool submit $pkg_path --keychain-profile jccm --wait
+
+                      echo "Stapling the Notarization Ticket to $pkg_path..."
+                      xcrun stapler staple $pkg_path
+
+                      echo "Verifying the Notarization of $pkg_path..."
+                      spctl -a -t install -vv $pkg_path
+                  }
+
+                  # Log in to Notarytool
+                  echo "Storing notary credentials..."
+                  xcrun notarytool store-credentials jccm --apple-id $APPLE_ID --team-id ${APPLE_DEVELOPER_TEAM_ID} --password ${APPLE_APP_SPECIFIC_PASSWORD}
+
+                  # Notarize and verify for both architectures
+                  notarize_and_verify "arm64"
+                  notarize_and_verify "x64"
+
+                  set +x  # Stop printing commands
               working-directory: ./jccm
 
             - name: Upload macOS artifacts
@@ -74,12 +119,12 @@ jobs:
               with:
                   name: macos-installers
                   path: |
-                      ./jccm/out/make/jccm-darwin-x64.dmg
-                      ./jccm/out/make/jccm-darwin-arm64.dmg
+                      ./jccm/out/make/*.dmg
+                      ./jccm/out/make/*.pkg
+
     build-windows:
         needs: build-macos
         runs-on: windows-latest
-        if: ${{ github.event.head_commit.message != 'Automated commit by GitHub Actions' }}
         steps:
             - uses: actions/checkout@v2
 
@@ -103,6 +148,7 @@ jobs:
                   path: |
                       ./jccm/out/make/squirrel.windows/x64/*.exe
                       ./jccm/out/make/squirrel.windows/x64/*.msi
+
     release:
         needs: [build-macos, build-windows]
         runs-on: ubuntu-latest
@@ -110,26 +156,13 @@ jobs:
             - name: Check out repository
               uses: actions/checkout@v2
 
-            - name: Set up Node.js
-              uses: actions/setup-node@v2
-              with:
-                  node-version: '20.10.0'
-
             - name: Read version from package.json
-              id: get_version
               run: echo "VERSION=$(jq -r '.version' ./jccm/package.json)" >> $GITHUB_ENV
 
-            - name: Download macOS artifacts
+            - name: Download Artifacts
               uses: actions/download-artifact@v2
               with:
-                  name: macos-installers
-                  path: ./installers/macos
-
-            - name: Download windows artifacts
-              uses: actions/download-artifact@v2
-              with:
-                  name: windows-installers
-                  path: ./installers/windows
+                  path: ./installers
 
             - name: Install GitHub CLI
               run: sudo apt-get install gh
@@ -153,32 +186,8 @@ jobs:
                   draft: false
                   prerelease: false
 
-            - name: Upload macOS x64 Release Asset
-              uses: actions/upload-release-asset@v1
+            - name: Upload Release Assets
+              run: |
+                  find ./installers -type f -exec echo "Uploading {}..." \; -exec gh release upload ${{ env.VERSION }} "{}" --clobber \;
               env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              with:
-                  upload_url: ${{ steps.create_release.outputs.upload_url }}
-                  asset_path: ./installers/macos/jccm-darwin-x64.dmg
-                  asset_name: jccm-darwin-x64.dmg
-                  asset_content_type: application/octet-stream
-
-            - name: Upload macOS arm64 Release Asset
-              uses: actions/upload-release-asset@v1
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              with:
-                  upload_url: ${{ steps.create_release.outputs.upload_url }}
-                  asset_path: ./installers/macos/jccm-darwin-arm64.dmg
-                  asset_name: jccm-darwin-arm64.dmg
-                  asset_content_type: application/octet-stream
-
-            - name: Upload Windows Release Asset
-              uses: actions/upload-release-asset@v1
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              with:
-                  upload_url: ${{ steps.create_release.outputs.upload_url }}
-                  asset_path: ./installers/windows/jccm-windows-x64-setup.exe
-                  asset_name: jccm-windows-x64-setup.exe
-                  asset_content_type: application/octet-stream
